//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chimera.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chimera.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap About_Box_Logo_Image {
            get {
                object obj = ResourceManager.GetObject("About_Box_Logo_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap About_Button {
            get {
                object obj = ResourceManager.GetObject("About_Button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Alt과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AltModifierKey {
            get {
                return ResourceManager.GetString("AltModifierKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Multi Monitor Manager과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Browse {
            get {
                object obj = ResourceManager.GetObject("Browse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Center과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Checkbox_Checked {
            get {
                object obj = ResourceManager.GetObject("Checkbox_Checked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Checkbox_Not_Checked {
            get {
                object obj = ResourceManager.GetObject("Checkbox_Not_Checked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Checkbox_Unselected {
            get {
                object obj = ResourceManager.GetObject("Checkbox_Unselected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   EnableCursorFeature과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigItem_EnableCursorFeature {
            get {
                return ResourceManager.GetString("ConfigItem_EnableCursorFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EnableLockCursorToScreen과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigItem_EnableLockCursorToScreen {
            get {
                return ResourceManager.GetString("ConfigItem_EnableLockCursorToScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EnableMoveCursorNextScreen과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigItem_EnableMoveCursorNextScreen {
            get {
                return ResourceManager.GetString("ConfigItem_EnableMoveCursorNextScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EnableMoveCursorPrevScreen과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigItem_EnableMoveCursorPrevScreen {
            get {
                return ResourceManager.GetString("ConfigItem_EnableMoveCursorPrevScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EnableMoveCursorPrimaryScreen과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigItem_EnableMoveCursorPrimaryScreen {
            get {
                return ResourceManager.GetString("ConfigItem_EnableMoveCursorPrimaryScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HotkeyLockCursorToScreen과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigItem_HotkeyLockCursorToScreen {
            get {
                return ResourceManager.GetString("ConfigItem_HotkeyLockCursorToScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HotkeyMoveCursorNextScreen과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigItem_HotkeyMoveCursorNextScreen {
            get {
                return ResourceManager.GetString("ConfigItem_HotkeyMoveCursorNextScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HotkeyMoveCursorPrevScreen과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigItem_HotkeyMoveCursorPrevScreen {
            get {
                return ResourceManager.GetString("ConfigItem_HotkeyMoveCursorPrevScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HotkeyMoveCursorPrimaryScreen과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigItem_HotkeyMoveCursorPrimaryScreen {
            get {
                return ResourceManager.GetString("ConfigItem_HotkeyMoveCursorPrimaryScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ctrl과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CtrlModifierKey {
            get {
                return ResourceManager.GetString("CtrlModifierKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current_Wallpaper.bmp과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CurrentWallPaperFileName {
            get {
                return ResourceManager.GetString("CurrentWallPaperFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Cursor_Control_Button {
            get {
                object obj = ResourceManager.GetObject("Cursor_Control_Button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Cursor_Control_Text {
            get {
                object obj = ResourceManager.GetObject("Cursor_Control_Text", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Move Cursor To Next Screen과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CursorNextScreenDescription {
            get {
                return ResourceManager.GetString("CursorNextScreenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CursorNextScreenWin7 {
            get {
                return ResourceManager.GetString("CursorNextScreenWin7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move Cursor To Previous Screen과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CursorPrevScreenDescription {
            get {
                return ResourceManager.GetString("CursorPrevScreenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CursorPrevScreenWin7 {
            get {
                return ResourceManager.GetString("CursorPrevScreenWin7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move Cursor to Primary Screen과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CursorPrimaryScreenDescription {
            get {
                return ResourceManager.GetString("CursorPrimaryScreenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CursorPrimaryScreenWin7 {
            get {
                return ResourceManager.GetString("CursorPrimaryScreenWin7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   --DISABLED--과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DisabledHotKey {
            get {
                return ResourceManager.GetString("DisabledHotKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Exclamation_Mark {
            get {
                object obj = ResourceManager.GetObject("Exclamation_Mark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   5002과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HIGH_SPEED_PID {
            get {
                return ResourceManager.GetString("HIGH_SPEED_PID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This hotkey is already registered.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HOT_KEY_DUPLICATED_MESSAGE {
            get {
                return ResourceManager.GetString("HOT_KEY_DUPLICATED_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Icon_Laptop {
            get {
                object obj = ResourceManager.GetObject("Icon_Laptop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Icon_Monitor {
            get {
                object obj = ResourceManager.GetObject("Icon_Monitor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] LGSmHaB {
            get {
                object obj = ResourceManager.GetObject("LGSmHaB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] LGSmHaL {
            get {
                object obj = ResourceManager.GetObject("LGSmHaL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] LGSmHaR {
            get {
                object obj = ResourceManager.GetObject("LGSmHaR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] LGSmHaSB {
            get {
                object obj = ResourceManager.GetObject("LGSmHaSB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Cursor Movement Between Screens is Lock과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LockCursorDescription {
            get {
                return ResourceManager.GetString("LockCursorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LockCursorWin7 {
            get {
                return ResourceManager.GetString("LockCursorWin7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Manager_Form_Icon {
            get {
                object obj = ResourceManager.GetObject("Manager_Form_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Icon Manager_Form_Icon1 {
            get {
                object obj = ResourceManager.GetObject("Manager_Form_Icon1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Mange_Button {
            get {
                object obj = ResourceManager.GetObject("Mange_Button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   You need to select a key from the drop down box과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NoKey {
            get {
                return ResourceManager.GetString("NoKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   For future combatibility with Windows 7 and later, you may want to use {0} for this function, as this is what Windows 7 uses.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NotWin7 {
            get {
                return ResourceManager.GetString("NotWin7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image Files (*.bmp, *.jpg, *.jpeg, *.png, *.gif)|*.bmp;*.jpg;*.jpeg;*.png;*.gif과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OpenImageFilter {
            get {
                return ResourceManager.GetString("OpenImageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fill과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OverStretch {
            get {
                return ResourceManager.GetString("OverStretch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LG USB-Hub Manager과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PRODUCT_NAME {
            get {
                return ResourceManager.GetString("PRODUCT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Icon Program_Icon {
            get {
                object obj = ResourceManager.GetObject("Program_Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   The registration of this hotkey has failed.
        ///Try another hot key combination.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RegisterFail {
            get {
                return ResourceManager.GetString("RegisterFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Reset_Disabled {
            get {
                object obj = ResourceManager.GetObject("Reset_Disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Reset_Enabled {
            get {
                object obj = ResourceManager.GetObject("Reset_Enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Select {
            get {
                object obj = ResourceManager.GetObject("Select", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Select_Trans {
            get {
                object obj = ResourceManager.GetObject("Select_Trans", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Setting Hotkey과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SETTING_HOTKEY {
            get {
                return ResourceManager.GetString("SETTING_HOTKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shift과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ShiftModifierKey {
            get {
                return ResourceManager.GetString("ShiftModifierKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stretch과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Stretch {
            get {
                return ResourceManager.GetString("Stretch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   5003과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SUPER_SPEED_PID {
            get {
                return ResourceManager.GetString("SUPER_SPEED_PID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Toggle_Switch_Off {
            get {
                object obj = ResourceManager.GetObject("Toggle_Switch_Off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Toggle_Switch_On {
            get {
                object obj = ResourceManager.GetObject("Toggle_Switch_On", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   001480과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UD5_ETHERNET_MAC_ADDRESS_PREFIX {
            get {
                return ResourceManager.GetString("UD5_ETHERNET_MAC_ADDRESS_PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Realtek USB GbE Family Controller과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UD5_ETHERNET_NAME {
            get {
                return ResourceManager.GetString("UD5_ETHERNET_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UnderStretch {
            get {
                return ResourceManager.GetString("UnderStretch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   152E과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VID {
            get {
                return ResourceManager.GetString("VID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Wallpaper_Button {
            get {
                object obj = ResourceManager.GetObject("Wallpaper_Button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   This functionality is already provided by Windows 7 using {0}, so there is no need to enable this unless you want SwapScreen to handle it using a different hotkey.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Win7 {
            get {
                return ResourceManager.GetString("Win7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Win과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WinModifierKey {
            get {
                return ResourceManager.GetString("WinModifierKey", resourceCulture);
            }
        }
    }
}
